import {
  CDIDataState,
  Rol,
  Usuario,
  Departamento,
  Cargo,
  Empleado,
  Horario,
  Paciente,
  Proveedor,
  Medicamento,
  MovimientoFarmacia,
  Cita,
  Tratamiento
} from '../types';

import {
  initialOrdenesLaboratorio,
  initialEstudiosImagen,
  initialCamasHospitalarias,
  initialAdmisionesHospitalarias,
  initialRegistrosTriaje,
  initialOdontogramas,
  initialTeleconsultas,
  initialInterconsultas,
  initialServiciosTarifas,
  initialFacturas,
  initialRegistrosAuditoria,
  initialCasosEpidemiologicos
} from './clinicalSeedData';

export const initialRoles: Rol[] = [
  {
    id: 'rol-1',
    nombre: 'Administrador',
    descripcion: 'Acceso total y control de configuración del CDI',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      pacientes: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      citas: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      triaje: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      tratamientos: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      laboratorio: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      imagenologia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      hospitalizacion: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      odontologia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      telemedicina: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      medicamentos: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      farmacia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      proveedores: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      facturacion: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      epidemiologia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      departamentos: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      empleados: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      cargos: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      horarios: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      usuarios: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      roles: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      auditoria: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      portal_paciente: { ver: true, crear: true, editar: true, eliminar: true, exportar: true }
    }
  },
  {
    id: 'rol-2',
    nombre: 'Médico',
    descripcion: 'Gestión clínica de pacientes, historias, citas, tratamientos, interconsultas y hospitalización',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      citas: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      triaje: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      tratamientos: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      laboratorio: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      imagenologia: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      hospitalizacion: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      odontologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      medicamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      farmacia: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      epidemiologia: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-3',
    nombre: 'Enfermero/a',
    descripcion: 'Triaje NEWS2, toma de signos vitales, administración de fármacos y censo de camas',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      pacientes: { ver: true, crear: true, editar: true, eliminar: false, exportar: false },
      citas: { ver: true, crear: true, editar: true, eliminar: false, exportar: false },
      triaje: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      tratamientos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      laboratorio: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      imagenologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      hospitalizacion: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      epidemiologia: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-4',
    nombre: 'Farmacéutico/a',
    descripcion: 'Control absoluto del stock, lotes, vademécum y dispensación de medicamentos',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      citas: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      triaje: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      laboratorio: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      imagenologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      hospitalizacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      farmacia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      proveedores: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      facturacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      epidemiologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-7',
    nombre: 'Bioanalista',
    descripcion: 'Gestión y validación de análisis clínicos y pruebas de laboratorio (LIS)',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      citas: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      triaje: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      laboratorio: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      imagenologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      hospitalizacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      epidemiologia: { ver: true, crear: true, editar: false, eliminar: false, exportar: true },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-8',
    nombre: 'Radiólogo/a',
    descripcion: 'Interpretación de estudios radiológicos, ecografías y tomografías (RIS/PACS)',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      citas: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      triaje: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      laboratorio: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      imagenologia: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      hospitalizacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      epidemiologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-9',
    nombre: 'Odontólogo/a',
    descripcion: 'Salud bucal, odontogramas anatómicos y tratamientos dentales',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      citas: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      triaje: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      laboratorio: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      imagenologia: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      hospitalizacion: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      telemedicina: { ver: true, crear: true, editar: true, eliminar: false, exportar: false },
      medicamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: true, crear: true, editar: false, eliminar: false, exportar: true },
      epidemiologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-5',
    nombre: 'Recepcionista',
    descripcion: 'Recepción de pacientes, asignación de citas, facturación y triaje preliminar',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      pacientes: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      citas: { ver: true, crear: true, editar: true, eliminar: true, exportar: true },
      triaje: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      laboratorio: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      imagenologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      hospitalizacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: true, crear: true, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: true, crear: true, editar: true, eliminar: false, exportar: true },
      epidemiologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: false, crear: false, editar: false, eliminar: false, exportar: false }
    }
  },
  {
    id: 'rol-6',
    nombre: 'Auditor',
    descripcion: 'Inspección, trazabilidad y reportes de todos los módulos sin permisos de modificación',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      pacientes: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      citas: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      triaje: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      tratamientos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      laboratorio: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      imagenologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      hospitalizacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      odontologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      telemedicina: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      medicamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      farmacia: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      proveedores: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      facturacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      epidemiologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      departamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      empleados: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      cargos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      horarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      usuarios: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      roles: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      auditoria: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      portal_paciente: { ver: true, crear: false, editar: false, eliminar: false, exportar: true }
    }
  },
  {
    id: 'rol-10',
    nombre: 'Paciente',
    descripcion: 'Portal de autoservicio para consulta de resultados, citas y recetas',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
    permisos: {
      dashboard: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      pacientes: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      citas: { ver: true, crear: true, editar: false, eliminar: false, exportar: true },
      triaje: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      tratamientos: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      laboratorio: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      imagenologia: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      hospitalizacion: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      odontologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      telemedicina: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      medicamentos: { ver: true, crear: false, editar: false, eliminar: false, exportar: false },
      farmacia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      proveedores: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      facturacion: { ver: true, crear: false, editar: false, eliminar: false, exportar: true },
      epidemiologia: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      departamentos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      empleados: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      cargos: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      horarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      usuarios: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      roles: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      auditoria: { ver: false, crear: false, editar: false, eliminar: false, exportar: false },
      portal_paciente: { ver: true, crear: true, editar: true, eliminar: false, exportar: true }
    }
  }
];


export const initialDepartamentos: Departamento[] = [
  {
    id: 'dep-1',
    codigo: 'EMERG',
    nombre: 'Emergencia y Triaje',
    descripcion: 'Atención médica inmediata las 24 horas y estabilización',
    piso: 'Planta Baja - Ala Norte',
    responsable: 'Dr. Roberto Gómez',
    capacidadCamas: 14,
    consultorios: 3,
    telefonoInterno: '101',
    estado: 'Activo'
  },
  {
    id: 'dep-2',
    codigo: 'MEDGEN',
    nombre: 'Medicina General y Consulta Externa',
    descripcion: 'Consultas integrales, chequeos preventivos y seguimiento ambulatorio',
    piso: 'Piso 1 - Módulo A',
    responsable: 'Dra. Elena Ramos',
    capacidadCamas: 0,
    consultorios: 6,
    telefonoInterno: '102',
    estado: 'Activo'
  },
  {
    id: 'dep-3',
    codigo: 'CARDIO',
    nombre: 'Cardiología y Electrocardiografía',
    descripcion: 'Evaluación cardiovascular, ecocardiogramas y pruebas de esfuerzo',
    piso: 'Piso 1 - Módulo B',
    responsable: 'Dr. Carlos Mendoza',
    capacidadCamas: 4,
    consultorios: 2,
    telefonoInterno: '103',
    estado: 'Activo'
  },
  {
    id: 'dep-4',
    codigo: 'LAB',
    nombre: 'Laboratorio Clínico y Bioanálisis',
    descripcion: 'Hematología completa, química sanguínea, serología y urocultivos',
    piso: 'Planta Baja - Ala Este',
    responsable: 'Lcda. Mariana Rivas',
    capacidadCamas: 0,
    consultorios: 2,
    telefonoInterno: '104',
    estado: 'Activo'
  },
  {
    id: 'dep-5',
    codigo: 'RX',
    nombre: 'Imagenología y Rayos X',
    descripcion: 'Radiografías digitales simples y contrastadas, ecografía Doppler',
    piso: 'Sótano 1 - Módulo Radiológico',
    responsable: 'Téc. Andrés Paredes',
    capacidadCamas: 2,
    consultorios: 2,
    telefonoInterno: '105',
    estado: 'Activo'
  },
  {
    id: 'dep-6',
    codigo: 'FARM',
    nombre: 'Farmacia Central y Dispensación',
    descripcion: 'Almacenamiento, control de inventario y entrega de medicamentos a pacientes',
    piso: 'Planta Baja - Pasillo Principal',
    responsable: 'Farm. Luisana Soto',
    capacidadCamas: 0,
    consultorios: 1,
    telefonoInterno: '106',
    estado: 'Activo'
  },
  {
    id: 'dep-7',
    codigo: 'ODONTO',
    nombre: 'Odontología y Salud Bucal',
    descripcion: 'Odontología integral, operatoria dental, endodoncia y periodoncia',
    piso: 'Piso 1 - Módulo C',
    responsable: 'Dra. Valeria Fuentes',
    capacidadCamas: 0,
    consultorios: 2,
    telefonoInterno: '107',
    estado: 'Activo'
  },
  {
    id: 'dep-8',
    codigo: 'HOSP',
    nombre: 'Hospitalización y Cuidados Críticos',
    descripcion: 'Salas de observación, medicina interna, aislamiento y cuidados intensivos',
    piso: 'Piso 2 - Ala Hospitalaria',
    responsable: 'Dr. Roberto Gómez',
    capacidadCamas: 24,
    consultorios: 1,
    telefonoInterno: '108',
    estado: 'Activo'
  },
  {
    id: 'dep-9',
    codigo: 'TELEMED',
    nombre: 'Telemedicina y Salud Digital',
    descripcion: 'Consultas médicas remotas, interconsultas especializadas y seguimiento virtual',
    piso: 'Piso 1 - Centro de Datos',
    responsable: 'Dra. Elena Ramos',
    capacidadCamas: 0,
    consultorios: 3,
    telefonoInterno: '109',
    estado: 'Activo'
  }
];

export const initialCargos: Cargo[] = [
  {
    id: 'car-1',
    titulo: 'Director Médico de CDI',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    nivelJerarquico: 'Directivo',
    salarioBase: 1200,
    requisitos: 'Médico Cirujano con Especialidad y +5 años en gestión sanitaria',
    descripcion: 'Dirección operativa, protocolos médicos y supervisión asistencial del centro',
    estado: 'Activo'
  },
  {
    id: 'car-2',
    titulo: 'Médico Especialista en Cardiología',
    departamentoId: 'dep-3',
    departamentoNombre: 'Cardiología y Electrocardiografía',
    nivelJerarquico: 'Médico Especialista',
    salarioBase: 950,
    requisitos: 'Postgrado en Cardiología, Colegiatura vigente y RIF',
    descripcion: 'Diagnóstico cardiológico, interpretación de ECG y atención especializada',
    estado: 'Activo'
  },
  {
    id: 'car-3',
    titulo: 'Médico General de Guardia',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    nivelJerarquico: 'Médico Especialista',
    salarioBase: 800,
    requisitos: 'Título Médico Cirujano y certificación en soporte vital avanzado (ACLS)',
    descripcion: 'Atención médica en emergencias, triaje y estabilización de pacientes',
    estado: 'Activo'
  },
  {
    id: 'car-4',
    titulo: 'Licenciado/a en Enfermería Jefe',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    nivelJerarquico: 'Asistencial',
    salarioBase: 650,
    requisitos: 'Licenciatura en Enfermería con experiencia en emergencias hospitalarias',
    descripcion: 'Supervisión del equipo de enfermería, suministros clínicos y atención directa',
    estado: 'Activo'
  },
  {
    id: 'car-5',
    titulo: 'Farmacéutico/a Regente',
    departamentoId: 'dep-6',
    departamentoNombre: 'Farmacia Central y Dispensación',
    nivelJerarquico: 'Técnico',
    salarioBase: 700,
    requisitos: 'Licenciatura en Farmacia con matrícula profesional activa',
    descripcion: 'Control de psicotrópicos, cadena de frío, lotes y dispensación de recetas',
    estado: 'Activo'
  },
  {
    id: 'car-6',
    titulo: 'Técnico Superior en Radiología',
    departamentoId: 'dep-5',
    departamentoNombre: 'Imagenología y Rayos X',
    nivelJerarquico: 'Técnico',
    salarioBase: 600,
    requisitos: 'TSU en Radiología e Imagenología Médica con permiso radiológico',
    descripcion: 'Operación de equipos radiológicos y protección radiológica',
    estado: 'Activo'
  },
  {
    id: 'car-7',
    titulo: 'Licenciado/a en Bioanálisis',
    departamentoId: 'dep-4',
    departamentoNombre: 'Laboratorio Clínico y Bioanálisis',
    nivelJerarquico: 'Técnico',
    salarioBase: 680,
    requisitos: 'Título de Bioanalista y experiencia en reactivos y procesadores automáticos',
    descripcion: 'Procesamiento de muestras hematológicas y emisión de reportes',
    estado: 'Activo'
  },
  {
    id: 'car-8',
    titulo: 'Asistente de Admisión y Recepción',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    nivelJerarquico: 'Administrativo',
    salarioBase: 450,
    requisitos: 'Bachiller / TSU con manejo de sistemas de historias clínicas y atención al público',
    descripcion: 'Apertura de historias clínicas, asignación de turnos y citas',
    estado: 'Activo'
  },
  {
    id: 'car-9',
    titulo: 'Odontólogo/a Integral',
    departamentoId: 'dep-7',
    departamentoNombre: 'Odontología y Salud Bucal',
    nivelJerarquico: 'Médico Especialista',
    salarioBase: 850,
    requisitos: 'Odontólogo graduado con colegiatura vigente',
    descripcion: 'Atención bucodental integral, operatoria y endodoncias',
    estado: 'Activo'
  }
];

export const initialEmpleados: Empleado[] = [
  {
    id: 'emp-1',
    cedula: 'V-14892104',
    nombres: 'Elena Beatriz',
    apellidos: 'Ramos Salazar',
    genero: 'Femenino',
    fechaNacimiento: '1985-06-14',
    email: 'elena.ramos@cdisalud.gob',
    telefono: '+58 414-2345678',
    direccion: 'Av. Andrés Bello, Residencias Los Álamos, Apto 4B',
    cargoId: 'car-1',
    cargoTitulo: 'Director Médico de CDI',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    fechaIngreso: '2020-03-01',
    colegiaturaMedica: 'MPPS-54210',
    estado: 'Activo'
  },
  {
    id: 'emp-2',
    cedula: 'V-12489032',
    nombres: 'Carlos Eduardo',
    apellidos: 'Mendoza Gutiérrez',
    genero: 'Masculino',
    fechaNacimiento: '1980-11-22',
    email: 'carlos.mendoza@cdisalud.gob',
    telefono: '+58 412-8765432',
    direccion: 'Urb. Santa Mónica, Calle Teresa de la Parra, Quinta Ávila',
    cargoId: 'car-2',
    cargoTitulo: 'Médico Especialista en Cardiología',
    departamentoId: 'dep-3',
    departamentoNombre: 'Cardiología y Electrocardiografía',
    fechaIngreso: '2019-06-15',
    colegiaturaMedica: 'MPPS-48901',
    estado: 'Activo'
  },
  {
    id: 'emp-3',
    cedula: 'V-16789412',
    nombres: 'Roberto Antonio',
    apellidos: 'Gómez Briceño',
    genero: 'Masculino',
    fechaNacimiento: '1988-03-08',
    email: 'roberto.gomez@cdisalud.gob',
    telefono: '+58 416-5544332',
    direccion: 'Sector El Paraíso, Edif. Centenario, Piso 3',
    cargoId: 'car-3',
    cargoTitulo: 'Médico General de Guardia',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    fechaIngreso: '2022-01-15',
    colegiaturaMedica: 'MPPS-78102',
    estado: 'Activo'
  },
  {
    id: 'emp-4',
    cedula: 'V-20194821',
    nombres: 'Patricia Carolina',
    apellidos: 'Silva Márquez',
    genero: 'Femenino',
    fechaNacimiento: '1992-09-17',
    email: 'patricia.silva@cdisalud.gob',
    telefono: '+58 424-1122334',
    direccion: 'Av. Urdaneta, Residencias Sol de Oro',
    cargoId: 'car-4',
    cargoTitulo: 'Licenciado/a en Enfermería Jefe',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    fechaIngreso: '2021-08-01',
    colegiaturaMedica: 'CPE-34901',
    estado: 'Activo'
  },
  {
    id: 'emp-5',
    cedula: 'V-19348271',
    nombres: 'Luisana Del Carmen',
    apellidos: 'Soto Quintero',
    genero: 'Femenino',
    fechaNacimiento: '1990-12-05',
    email: 'luisana.soto@cdisalud.gob',
    telefono: '+58 414-9988776',
    direccion: 'Urb. Cumbres de Curumo, Calle B',
    cargoId: 'car-5',
    cargoTitulo: 'Farmacéutico/a Regente',
    departamentoId: 'dep-6',
    departamentoNombre: 'Farmacia Central y Dispensación',
    fechaIngreso: '2021-03-15',
    colegiaturaMedica: 'COLFAR-1289',
    estado: 'Activo'
  },
  {
    id: 'emp-6',
    cedula: 'V-21448902',
    nombres: 'Andrés Eloy',
    apellidos: 'Paredes Rivas',
    genero: 'Masculino',
    fechaNacimiento: '1994-07-29',
    email: 'andres.paredes@cdisalud.gob',
    telefono: '+58 412-3344556',
    direccion: 'Sector San Bernardino, Qta. Los Rosales',
    cargoId: 'car-6',
    cargoTitulo: 'Técnico Superior en Radiología',
    departamentoId: 'dep-5',
    departamentoNombre: 'Imagenología y Rayos X',
    fechaIngreso: '2023-02-01',
    estado: 'Activo'
  },
  {
    id: 'emp-7',
    cedula: 'V-22109432',
    nombres: 'Mariana Isabel',
    apellidos: 'Rivas Delgado',
    genero: 'Femenino',
    fechaNacimiento: '1995-04-12',
    email: 'mariana.rivas@cdisalud.gob',
    telefono: '+58 416-7788990',
    direccion: 'Av. Sucre, Los Dos Caminos',
    cargoId: 'car-7',
    cargoTitulo: 'Licenciado/a en Bioanálisis',
    departamentoId: 'dep-4',
    departamentoNombre: 'Laboratorio Clínico y Bioanálisis',
    fechaIngreso: '2022-09-15',
    colegiaturaMedica: 'CBV-8942',
    estado: 'Activo'
  },
  {
    id: 'emp-8',
    cedula: 'V-24589012',
    nombres: 'Carmen Teresa',
    apellidos: 'Flores Blanco',
    genero: 'Femenino',
    fechaNacimiento: '1997-10-03',
    email: 'carmen.flores@cdisalud.gob',
    telefono: '+58 424-6655443',
    direccion: 'Sector La Candelaria, Edf. Bolívar',
    cargoId: 'car-8',
    cargoTitulo: 'Asistente de Admisión y Recepción',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    fechaIngreso: '2023-05-10',
    estado: 'Activo'
  },
  {
    id: 'emp-9',
    cedula: 'V-23890451',
    nombres: 'Valeria Sofía',
    apellidos: 'Fuentes Morales',
    genero: 'Femenino',
    fechaNacimiento: '1993-08-21',
    email: 'valeria.fuentes@cdisalud.gob',
    telefono: '+58 414-7766554',
    direccion: 'Av. Libertador, Torre Maracaibo, Piso 6',
    cargoId: 'car-9',
    cargoTitulo: 'Odontólogo/a Integral',
    departamentoId: 'dep-7',
    departamentoNombre: 'Odontología y Salud Bucal',
    fechaIngreso: '2022-11-01',
    colegiaturaMedica: 'COV-19842',
    estado: 'Activo'
  }
];

export const initialUsuarios: Usuario[] = [
  {
    id: 'usr-1',
    nombreUsuario: 'admin',
    nombreCompleto: 'Administrador del CDI',
    email: 'admin@cdisalud.gob',
    telefono: '+58 414-0001122',
    rolId: 'rol-1',
    rolNombre: 'Administrador',
    empleadoId: 'emp-1',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 08:30',
    fechaCreacion: '2025-01-01'
  },
  {
    id: 'usr-2',
    nombreUsuario: 'dr.carlos',
    nombreCompleto: 'Dr. Carlos Mendoza',
    email: 'carlos.mendoza@cdisalud.gob',
    telefono: '+58 412-8765432',
    rolId: 'rol-2',
    rolNombre: 'Médico',
    empleadoId: 'emp-2',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 09:15',
    fechaCreacion: '2025-01-05'
  },
  {
    id: 'usr-3',
    nombreUsuario: 'dra.elena',
    nombreCompleto: 'Dra. Elena Ramos',
    email: 'elena.ramos@cdisalud.gob',
    telefono: '+58 414-2345678',
    rolId: 'rol-2',
    rolNombre: 'Médico',
    empleadoId: 'emp-1',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 07:45',
    fechaCreacion: '2025-01-05'
  },
  {
    id: 'usr-4',
    nombreUsuario: 'enf.patricia',
    nombreCompleto: 'Lic. Patricia Silva',
    email: 'patricia.silva@cdisalud.gob',
    telefono: '+58 424-1122334',
    rolId: 'rol-3',
    rolNombre: 'Enfermero/a',
    empleadoId: 'emp-4',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 07:00',
    fechaCreacion: '2025-01-08'
  },
  {
    id: 'usr-5',
    nombreUsuario: 'farm.luisana',
    nombreCompleto: 'Farm. Luisana Soto',
    email: 'luisana.soto@cdisalud.gob',
    telefono: '+58 414-9988776',
    rolId: 'rol-4',
    rolNombre: 'Farmacéutico/a',
    empleadoId: 'emp-5',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 08:00',
    fechaCreacion: '2025-01-08'
  },
  {
    id: 'usr-7',
    nombreUsuario: 'bio.mariana',
    nombreCompleto: 'Lcda. Mariana Rivas',
    email: 'mariana.rivas@cdisalud.gob',
    telefono: '+58 416-7788990',
    rolId: 'rol-7',
    rolNombre: 'Bioanalista',
    empleadoId: 'emp-7',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 07:30',
    fechaCreacion: '2025-01-08'
  },
  {
    id: 'usr-8',
    nombreUsuario: 'rad.andres',
    nombreCompleto: 'Téc. Andrés Paredes',
    email: 'andres.paredes@cdisalud.gob',
    telefono: '+58 412-3344556',
    rolId: 'rol-8',
    rolNombre: 'Radiólogo/a',
    empleadoId: 'emp-6',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 08:15',
    fechaCreacion: '2025-01-08'
  },
  {
    id: 'usr-9',
    nombreUsuario: 'odo.valeria',
    nombreCompleto: 'Dra. Valeria Fuentes',
    email: 'valeria.fuentes@cdisalud.gob',
    telefono: '+58 414-7766554',
    rolId: 'rol-9',
    rolNombre: 'Odontólogo/a',
    empleadoId: 'emp-9',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 08:45',
    fechaCreacion: '2025-01-08'
  },
  {
    id: 'usr-6',
    nombreUsuario: 'recep.carmen',
    nombreCompleto: 'Carmen Flores',
    email: 'carmen.flores@cdisalud.gob',
    telefono: '+58 424-6655443',
    rolId: 'rol-5',
    rolNombre: 'Recepcionista',
    empleadoId: 'emp-8',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 06:50',
    fechaCreacion: '2025-01-10'
  },
  {
    id: 'usr-10',
    nombreUsuario: 'pac.jose',
    nombreCompleto: 'José Gregorio Hernández (Paciente)',
    email: 'jose.hernandez@correo.com',
    telefono: '+58 414-1234567',
    rolId: 'rol-10',
    rolNombre: 'Paciente',
    pacienteId: 'pac-1',
    estado: 'Activo',
    ultimoAcceso: '2025-02-15 09:00',
    fechaCreacion: '2025-01-15'
  }
];

export const initialHorarios: Horario[] = [
  {
    id: 'hor-1',
    nombreTurno: 'Mañana - Consulta Cardiología',
    empleadoId: 'emp-2',
    empleadoNombre: 'Dr. Carlos Mendoza',
    departamentoId: 'dep-3',
    departamentoNombre: 'Cardiología y Electrocardiografía',
    tipoTurno: 'Matutino',
    horaInicio: '07:00',
    horaFin: '13:00',
    diasSemana: ['Lunes', 'Miércoles', 'Viernes'],
    estado: 'Activo',
    observaciones: 'Evaluación de pacientes referidos y pruebas ECG'
  },
  {
    id: 'hor-2',
    nombreTurno: 'Tarde - Medicina General',
    empleadoId: 'emp-1',
    empleadoNombre: 'Dra. Elena Ramos',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    tipoTurno: 'Vespertino',
    horaInicio: '13:00',
    horaFin: '19:00',
    diasSemana: ['Lunes', 'Martes', 'Miércoles', 'Jueves'],
    estado: 'Activo',
    observaciones: 'Control de hipertensión, diabetes y chequeos'
  },
  {
    id: 'hor-3',
    nombreTurno: 'Guardia Emergencia 24H',
    empleadoId: 'emp-3',
    empleadoNombre: 'Dr. Roberto Gómez',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    tipoTurno: 'Guardia 24h',
    horaInicio: '08:00',
    horaFin: '08:00',
    diasSemana: ['Martes', 'Sábado'],
    estado: 'Activo',
    observaciones: 'Guardia médica completa de urgencias'
  },
  {
    id: 'hor-4',
    nombreTurno: 'Supervisión Enfermería Matutina',
    empleadoId: 'emp-4',
    empleadoNombre: 'Lic. Patricia Silva',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    tipoTurno: 'Matutino',
    horaInicio: '07:00',
    horaFin: '15:00',
    diasSemana: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    estado: 'Activo',
    observaciones: 'Jefe de guardia y administración de dosis'
  },
  {
    id: 'hor-5',
    nombreTurno: 'Despacho Farmacia Completo',
    empleadoId: 'emp-5',
    empleadoNombre: 'Farm. Luisana Soto',
    departamentoId: 'dep-6',
    departamentoNombre: 'Farmacia Central y Dispensación',
    tipoTurno: 'Matutino',
    horaInicio: '07:30',
    horaFin: '16:00',
    diasSemana: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    estado: 'Activo',
    observaciones: 'Recepción de lotes y despacho de fórmulas médicas'
  },
  {
    id: 'hor-6',
    nombreTurno: 'Turno Rayos X Matutino',
    empleadoId: 'emp-6',
    empleadoNombre: 'Téc. Andrés Paredes',
    departamentoId: 'dep-5',
    departamentoNombre: 'Imagenología y Rayos X',
    tipoTurno: 'Matutino',
    horaInicio: '07:00',
    horaFin: '13:00',
    diasSemana: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    estado: 'Activo',
    observaciones: 'Estudios de tórax, óseos y ecografías'
  }
];

export const initialPacientes: Paciente[] = [
  {
    id: 'pac-1',
    cedula: 'V-9874561',
    nombres: 'José Gregorio',
    apellidos: 'Hernández Morillo',
    fechaNacimiento: '1962-08-14',
    edad: 62,
    genero: 'Masculino',
    tipoSangre: 'O+',
    telefono: '+58 412-9876543',
    email: 'jose.hernandez@email.com',
    direccion: 'Sector 23 de Enero, Bloque 15, Caracas',
    contactoEmergencia: {
      nombre: 'María Hernández (Hija)',
      parentesco: 'Hija',
      telefono: '+58 414-3322110'
    },
    alergias: ['Penicilina', 'Sulfamidas'],
    antecedentes: ['Hipertensión Arterial Primaria (10 años)', 'Diabetes Mellitus Tipo 2'],
    fechaRegistro: '2023-03-12',
    estado: 'Activo'
  },
  {
    id: 'pac-2',
    cedula: 'V-15894210',
    nombres: 'Ana Gabriela',
    apellidos: 'Suárez Peña',
    fechaNacimiento: '1983-04-25',
    edad: 41,
    genero: 'Femenino',
    tipoSangre: 'A+',
    telefono: '+58 416-2211445',
    email: 'ana.suarez@email.com',
    direccion: 'Av. San Martín, Edif. Colonial, Apto 2-A',
    contactoEmergencia: {
      nombre: 'Ricardo Suárez (Esposo)',
      parentesco: 'Esposo',
      telefono: '+58 424-9988112'
    },
    alergias: ['AINES (Ibuprofeno)', 'Polen'],
    antecedentes: ['Asma Bronquial Leve'],
    fechaRegistro: '2023-06-20',
    estado: 'Activo'
  },
  {
    id: 'pac-3',
    cedula: 'V-23114589',
    nombres: 'Luis Alejandro',
    apellidos: 'Castillo Colmenares',
    fechaNacimiento: '1996-12-10',
    edad: 28,
    genero: 'Masculino',
    tipoSangre: 'B+',
    telefono: '+58 414-7744112',
    direccion: 'Barrio Unión, Calle Sucre, Casa 45',
    contactoEmergencia: {
      nombre: 'Carmen Colmenares (Madre)',
      parentesco: 'Madre',
      telefono: '+58 412-1144778'
    },
    alergias: ['Ninguna conocida'],
    antecedentes: ['Traumatismo de rodilla derecha (2021)'],
    fechaRegistro: '2024-01-14',
    estado: 'Activo'
  },
  {
    id: 'pac-4',
    cedula: 'V-6489123',
    nombres: 'Rosa María',
    apellidos: 'Guzmán de Lovera',
    fechaNacimiento: '1954-01-30',
    edad: 71,
    genero: 'Femenino',
    tipoSangre: 'AB+',
    telefono: '+58 414-8899221',
    direccion: 'Urb. El Marqués, Calle Araguaney',
    contactoEmergencia: {
      nombre: 'Gabriel Lovera (Hijo)',
      parentesco: 'Hijo',
      telefono: '+58 416-3366992'
    },
    alergias: ['Dipirona / Metamizol'],
    antecedentes: ['Insuficiencia Cardíaca Grado II', 'Osteoartritis'],
    fechaRegistro: '2022-11-05',
    estado: 'En Observación'
  },
  {
    id: 'pac-5',
    cedula: 'V-27891456',
    nombres: 'Valentina Sofía',
    apellidos: 'Torres Bello',
    fechaNacimiento: '2001-05-18',
    edad: 23,
    genero: 'Femenino',
    tipoSangre: 'O-',
    telefono: '+58 424-5566778',
    email: 'valentina.torres@email.com',
    direccion: 'Av. Baralt, Edif. Centro, Piso 7',
    contactoEmergencia: {
      nombre: 'Daniel Torres (Padre)',
      parentesco: 'Padre',
      telefono: '+58 414-6655112'
    },
    alergias: ['Ninguna conocida'],
    antecedentes: ['Migrañas recurrentes'],
    fechaRegistro: '2024-05-10',
    estado: 'Activo'
  }
];

export const initialProveedores: Proveedor[] = [
  {
    id: 'prov-1',
    rif: 'J-00012845-6',
    razonSocial: 'Laboratorios Behrens C.A.',
    nombreComercial: 'Laboratorios Behrens',
    contactoPrincipal: 'Dr. Fernando Salazar',
    telefono: '+58 212-2081111',
    email: 'ventas@behrens.com.ve',
    direccion: 'Zona Industrial La Trinidad, Calle 2, Caracas',
    ciudad: 'Caracas',
    categoria: 'Medicamentos',
    plazoPagoDias: 30,
    calificacion: 5,
    estado: 'Activo'
  },
  {
    id: 'prov-2',
    rif: 'J-00054812-9',
    razonSocial: 'Droguería Nena C.A.',
    nombreComercial: 'Droguería Nena',
    contactoPrincipal: 'Lic. Claudia Morales',
    telefono: '+58 212-3832000',
    email: 'institucional@droguerianena.com',
    direccion: 'Parque Industrial Las Tejerías, Galpón 4',
    ciudad: 'Las Tejerías',
    categoria: 'Medicamentos',
    plazoPagoDias: 45,
    calificacion: 5,
    estado: 'Activo'
  },
  {
    id: 'prov-3',
    rif: 'J-31489012-3',
    razonSocial: 'Suministros Médicos Quirúrgicos Nacional C.A.',
    nombreComercial: 'Sumedica',
    contactoPrincipal: 'Ing. Javier Rojas',
    telefono: '+58 212-9938822',
    email: 'ventas@sumedica.com.ve',
    direccion: 'Av. Francisco de Miranda, Torre Cavendes, Chacao',
    ciudad: 'Caracas',
    categoria: 'Material Médico-Quirúrgico',
    plazoPagoDias: 15,
    calificacion: 4,
    estado: 'Activo'
  },
  {
    id: 'prov-4',
    rif: 'J-29841029-1',
    razonSocial: 'Reactivos y Diagnósticos Clínicos C.A.',
    nombreComercial: 'Biodiagnóstica',
    contactoPrincipal: 'Lic. Marisol Vega',
    telefono: '+58 241-8321144',
    email: 'contacto@biodiagnostica.com.ve',
    direccion: 'Av. Bolívar Norte, Edf. Empresarial Valencia',
    ciudad: 'Valencia',
    categoria: 'Reactivos de Laboratorio',
    plazoPagoDias: 30,
    calificacion: 4,
    estado: 'Activo'
  }
];

export const initialMedicamentos: Medicamento[] = [
  {
    id: 'med-1',
    codigo: 'MED-LOS-50',
    nombreComercial: 'Losartán Potásico 50mg',
    principioActivo: 'Losartán Potásico',
    concentracion: '50 mg',
    presentacion: 'Tabletas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Antihipertensivo / ARA II',
    stockActual: 140,
    stockMinimo: 80,
    stockMaximo: 500,
    ubicacionEstante: 'Estante A-1, Nivel 2',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-2',
    codigo: 'MED-AML-10',
    nombreComercial: 'Amlodipino 10mg',
    principioActivo: 'Besilato de Amlodipino',
    concentracion: '10 mg',
    presentacion: 'Tabletas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Antihipertensivo / Calcioantagonista',
    stockActual: 24,
    stockMinimo: 50,
    stockMaximo: 300,
    ubicacionEstante: 'Estante A-1, Nivel 3',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Stock Bajo'
  },
  {
    id: 'med-3',
    codigo: 'MED-AMX-500',
    nombreComercial: 'Amoxicilina 500mg',
    principioActivo: 'Amoxicilina Trihidrato',
    concentracion: '500 mg',
    presentacion: 'Cápsulas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Antibiótico Betalactámico',
    stockActual: 320,
    stockMinimo: 100,
    stockMaximo: 600,
    ubicacionEstante: 'Estante B-2, Nivel 1',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-4',
    codigo: 'MED-MET-850',
    nombreComercial: 'Metformina Clorhidrato 850mg',
    principioActivo: 'Metformina Clorhidrato',
    concentracion: '850 mg',
    presentacion: 'Tabletas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Hipoglucemiante Oral',
    stockActual: 85,
    stockMinimo: 70,
    stockMaximo: 400,
    ubicacionEstante: 'Estante A-2, Nivel 1',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-5',
    codigo: 'MED-INS-NPH',
    nombreComercial: 'Insulina Humana NPH 100 UI/ml',
    principioActivo: 'Insulina Humana Recombinante',
    concentracion: '100 UI/ml',
    presentacion: 'Ampollas / Inyectable',
    viaAdministracion: 'Subcutánea',
    categoriaTerapeutica: 'Antidiabético Inyectable',
    stockActual: 12,
    stockMinimo: 30,
    stockMaximo: 150,
    ubicacionEstante: 'Nevera Farmacia 1 (2-8°C)',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Refrigerado (2-8°C)',
    estado: 'Stock Bajo'
  },
  {
    id: 'med-6',
    codigo: 'MED-PAR-500',
    nombreComercial: 'Paracetamol / Acetaminofén 500mg',
    principioActivo: 'Paracetamol',
    concentracion: '500 mg',
    presentacion: 'Tabletas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Analgésico / Antipirético',
    stockActual: 650,
    stockMinimo: 150,
    stockMaximo: 1200,
    ubicacionEstante: 'Estante C-1, Nivel 1',
    requiereReceta: false,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-7',
    codigo: 'MED-DEX-8MG',
    nombreComercial: 'Dexametasona 8mg/2ml',
    principioActivo: 'Dexametasona Fosfato Disódico',
    concentracion: '8 mg / 2 ml',
    presentacion: 'Ampollas / Inyectable',
    viaAdministracion: 'Intravenosa / Intramuscular',
    categoriaTerapeutica: 'Corticoesteroide Antiinflamatorio',
    stockActual: 90,
    stockMinimo: 40,
    stockMaximo: 250,
    ubicacionEstante: 'Estante C-2, Nivel 2',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-8',
    codigo: 'MED-OMP-20',
    nombreComercial: 'Omeprazol 20mg',
    principioActivo: 'Omeprazol Magnésico',
    concentracion: '20 mg',
    presentacion: 'Cápsulas',
    viaAdministracion: 'Oral',
    categoriaTerapeutica: 'Inhibidor de Bomba de Protones',
    stockActual: 210,
    stockMinimo: 80,
    stockMaximo: 500,
    ubicacionEstante: 'Estante A-3, Nivel 2',
    requiereReceta: false,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  },
  {
    id: 'med-9',
    codigo: 'MED-SAL-100',
    nombreComercial: 'Salbutamol Inhalador 100mcg',
    principioActivo: 'Sulfato de Salbutamol',
    concentracion: '100 mcg / dosis (200 dosis)',
    presentacion: 'Suspensión',
    viaAdministracion: 'Inhalatoria',
    categoriaTerapeutica: 'Broncodilatador Beta-2 Agonista',
    stockActual: 8,
    stockMinimo: 25,
    stockMaximo: 100,
    ubicacionEstante: 'Estante B-1, Nivel 3',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Stock Bajo'
  },
  {
    id: 'med-10',
    codigo: 'MED-SOL-09',
    nombreComercial: 'Solución Fisiológica 0.9% 500ml',
    principioActivo: 'Cloruro de Sodio 0.9%',
    concentracion: '0.9 g / 100 ml',
    presentacion: 'Solución Intravenosa',
    viaAdministracion: 'Intravenosa',
    categoriaTerapeutica: 'Solución Electrolítica Rehidratante',
    stockActual: 450,
    stockMinimo: 100,
    stockMaximo: 800,
    ubicacionEstante: 'Almacén Sueros, Tarima A',
    requiereReceta: true,
    temperaturaAlmacenamiento: 'Ambiente (15-25°C)',
    estado: 'Disponible'
  }
];

export const initialMovimientosFarmacia: MovimientoFarmacia[] = [
  {
    id: 'mov-1',
    numeroTransaccion: 'TRX-2025-00101',
    tipoMovimiento: 'Entrada / Compra',
    medicamentoId: 'med-1',
    medicamentoNombre: 'Losartán Potásico 50mg',
    cantidad: 200,
    lote: 'L-240801',
    fechaVencimiento: '2026-11-30',
    proveedorId: 'prov-1',
    proveedorNombre: 'Laboratorios Behrens',
    responsableEmpleadoId: 'emp-5',
    responsableNombre: 'Farm. Luisana Soto',
    fechaHora: '2025-02-10 10:15',
    motivo: 'Recepción de orden de compra nacional ordinaria',
    observaciones: 'Empaques sellados e inspección de calidad aprobada'
  },
  {
    id: 'mov-2',
    numeroTransaccion: 'TRX-2025-00102',
    tipoMovimiento: 'Salida / Despacho',
    medicamentoId: 'med-1',
    medicamentoNombre: 'Losartán Potásico 50mg',
    cantidad: 60,
    lote: 'L-240801',
    fechaVencimiento: '2026-11-30',
    pacienteId: 'pac-1',
    pacienteNombre: 'José Gregorio Hernández Morillo',
    tratamientoId: 'tra-1',
    responsableEmpleadoId: 'emp-5',
    responsableNombre: 'Farm. Luisana Soto',
    fechaHora: '2025-02-14 11:30',
    motivo: 'Dispensación mensual de tratamiento antihipertensivo',
    observaciones: 'Tratamiento verificado con receta firmada por Dra. Elena Ramos'
  },
  {
    id: 'mov-3',
    numeroTransaccion: 'TRX-2025-00103',
    tipoMovimiento: 'Salida / Despacho',
    medicamentoId: 'med-6',
    medicamentoNombre: 'Paracetamol / Acetaminofén 500mg',
    cantidad: 20,
    lote: 'L-240915',
    fechaVencimiento: '2027-05-30',
    pacienteId: 'pac-3',
    pacienteNombre: 'Luis Alejandro Castillo Colmenares',
    responsableEmpleadoId: 'emp-5',
    responsableNombre: 'Farm. Luisana Soto',
    fechaHora: '2025-02-15 08:45',
    motivo: 'Entrega ambulatoria para cuadro febril',
    observaciones: 'Se orientó al paciente sobre pauta de dosificación'
  },
  {
    id: 'mov-4',
    numeroTransaccion: 'TRX-2025-00104',
    tipoMovimiento: 'Entrada / Compra',
    medicamentoId: 'med-10',
    medicamentoNombre: 'Solución Fisiológica 0.9% 500ml',
    cantidad: 300,
    lote: 'L-250102',
    fechaVencimiento: '2027-12-31',
    proveedorId: 'prov-2',
    proveedorNombre: 'Droguería Nena',
    responsableEmpleadoId: 'emp-5',
    responsableNombre: 'Farm. Luisana Soto',
    fechaHora: '2025-02-12 14:00',
    motivo: 'Reposición para sala de trauma y choque de emergencia'
  }
];

export const initialCitas: Cita[] = [
  {
    id: 'cit-1',
    codigoCita: 'CIT-2025-0089',
    pacienteId: 'pac-1',
    pacienteNombre: 'José Gregorio Hernández Morillo',
    pacienteCedula: 'V-9874561',
    medicoId: 'emp-2',
    medicoNombre: 'Dr. Carlos Mendoza',
    departamentoId: 'dep-3',
    departamentoNombre: 'Cardiología y Electrocardiografía',
    fecha: '2025-02-15',
    hora: '08:30',
    motivoConsulta: 'Control de hipertensión y evaluación de ecocardiograma',
    triajePrioridad: 'Consulta Regular',
    signosVitales: {
      presionArterial: '135/85 mmHg',
      frecuenciaCardiaca: 74,
      temperatura: 36.5,
      saturacionOxigeno: 98,
      pesoKg: 78.5
    },
    estado: 'En Consulta',
    diagnosticoPreliminar: 'Cardiopatía hipertensiva compensada'
  },
  {
    id: 'cit-2',
    codigoCita: 'CIT-2025-0090',
    pacienteId: 'pac-4',
    pacienteNombre: 'Rosa María Guzmán de Lovera',
    pacienteCedula: 'V-6489123',
    medicoId: 'emp-3',
    medicoNombre: 'Dr. Roberto Gómez',
    departamentoId: 'dep-1',
    departamentoNombre: 'Emergencia y Triaje',
    fecha: '2025-02-15',
    hora: '09:00',
    motivoConsulta: 'Disnea de medianos esfuerzos y edema en miembros inferiores',
    triajePrioridad: 'Urgencia',
    signosVitales: {
      presionArterial: '150/95 mmHg',
      frecuenciaCardiaca: 88,
      temperatura: 36.8,
      saturacionOxigeno: 94,
      pesoKg: 65.0
    },
    estado: 'En Triaje',
    diagnosticoPreliminar: 'Descompensación por Insuficiencia Cardíaca'
  },
  {
    id: 'cit-3',
    codigoCita: 'CIT-2025-0091',
    pacienteId: 'pac-2',
    pacienteNombre: 'Ana Gabriela Suárez Peña',
    pacienteCedula: 'V-15894210',
    medicoId: 'emp-1',
    medicoNombre: 'Dra. Elena Ramos',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    fecha: '2025-02-15',
    hora: '10:00',
    motivoConsulta: 'Crisis broncoespástica leve y tos seca nocturna',
    triajePrioridad: 'Consulta Regular',
    signosVitales: {
      presionArterial: '120/80 mmHg',
      frecuenciaCardiaca: 80,
      temperatura: 36.6,
      saturacionOxigeno: 97,
      pesoKg: 58.0
    },
    estado: 'Confirmada'
  },
  {
    id: 'cit-4',
    codigoCita: 'CIT-2025-0092',
    pacienteId: 'pac-5',
    pacienteNombre: 'Valentina Sofía Torres Bello',
    pacienteCedula: 'V-27891456',
    medicoId: 'emp-1',
    medicoNombre: 'Dra. Elena Ramos',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    fecha: '2025-02-15',
    hora: '11:15',
    motivoConsulta: 'Cefalea hemicraneana pulsátil recurrente con náuseas',
    triajePrioridad: 'Consulta Regular',
    estado: 'Pendiente'
  },
  {
    id: 'cit-5',
    codigoCita: 'CIT-2025-0093',
    pacienteId: 'pac-3',
    pacienteNombre: 'Luis Alejandro Castillo Colmenares',
    pacienteCedula: 'V-23114589',
    medicoId: 'emp-1',
    medicoNombre: 'Dra. Elena Ramos',
    departamentoId: 'dep-2',
    departamentoNombre: 'Medicina General y Consulta Externa',
    fecha: '2025-02-14',
    hora: '15:30',
    motivoConsulta: 'Cuadro febril de 48h de evolución con malestar general',
    triajePrioridad: 'Consulta Regular',
    signosVitales: {
      presionArterial: '118/75 mmHg',
      frecuenciaCardiaca: 82,
      temperatura: 38.2,
      saturacionOxigeno: 99,
      pesoKg: 72.0
    },
    estado: 'Completada',
    diagnosticoPreliminar: 'Síndrome viral agudo'
  }
];

export const initialTratamientos: Tratamiento[] = [
  {
    id: 'tra-1',
    codigoTratamiento: 'TRAT-2025-0045',
    citaId: 'cit-1',
    pacienteId: 'pac-1',
    pacienteNombre: 'José Gregorio Hernández Morillo',
    pacienteCedula: 'V-9874561',
    medicoId: 'emp-2',
    medicoNombre: 'Dr. Carlos Mendoza',
    diagnosticoCIE: 'I10 - Hipertensión esencial (primaria)',
    diagnosticoDescripcion: 'Tratamiento de mantenimiento para control de cifras tensionales',
    prescripciones: [
      {
        medicamentoId: 'med-1',
        medicamentoNombre: 'Losartán Potásico 50mg',
        dosis: '50 mg (1 tableta)',
        frecuencia: 'Cada 12 horas (Mañana y Noche)',
        duracionDias: 60,
        cantidadTotal: 120,
        instruccionesEspeciales: 'Tomar con abundante agua después de las comidas'
      },
      {
        medicamentoId: 'med-4',
        medicamentoNombre: 'Metformina Clorhidrato 850mg',
        dosis: '850 mg (1 tableta)',
        frecuencia: 'Una vez al día con el almuerzo',
        duracionDias: 60,
        cantidadTotal: 60,
        instruccionesEspeciales: 'Mantener dieta baja en carbohidratos refinados'
      }
    ],
    indicacionesGenerales: 'Reducir consumo de sodio (<2g al día), caminata aeróbica 30 minutos diarios, control ambulatorio de presión arterial semanal.',
    fechaInicio: '2025-02-15',
    fechaFin: '2025-04-15',
    proximoControl: '2025-04-15',
    estado: 'Activo'
  },
  {
    id: 'tra-2',
    codigoTratamiento: 'TRAT-2025-0046',
    citaId: 'cit-5',
    pacienteId: 'pac-3',
    pacienteNombre: 'Luis Alejandro Castillo Colmenares',
    pacienteCedula: 'V-23114589',
    medicoId: 'emp-1',
    medicoNombre: 'Dra. Elena Ramos',
    diagnosticoCIE: 'B34.9 - Infección viral no especificada',
    diagnosticoDescripcion: 'Manejo sintomático de síndrome febril agudo',
    prescripciones: [
      {
        medicamentoId: 'med-6',
        medicamentoNombre: 'Paracetamol / Acetaminofén 500mg',
        dosis: '500 mg (1 tableta)',
        frecuencia: 'Cada 6 a 8 horas si hay fiebre o dolor',
        duracionDias: 5,
        cantidadTotal: 20,
        instruccionesEspeciales: 'No exceder 3 gramos al día'
      }
    ],
    indicacionesGenerales: 'Hidratación abundante oral (mínimo 2.5 litros de líquidos al día), reposo relativo por 72 horas. Consultar si hay signos de alarma.',
    fechaInicio: '2025-02-14',
    fechaFin: '2025-02-19',
    estado: 'Activo'
  }
];

export const getInitialDataState = (): CDIDataState => ({
  roles: initialRoles,
  usuarios: initialUsuarios,
  departamentos: initialDepartamentos,
  cargos: initialCargos,
  empleados: initialEmpleados,
  horarios: initialHorarios,
  pacientes: initialPacientes,
  proveedores: initialProveedores,
  medicamentos: initialMedicamentos,
  movimientosFarmacia: initialMovimientosFarmacia,
  citas: initialCitas,
  tratamientos: initialTratamientos,
  // Nuevas colecciones clínicas Enterprise
  ordenesLaboratorio: initialOrdenesLaboratorio,
  estudiosImagen: initialEstudiosImagen,
  camasHospitalarias: initialCamasHospitalarias,
  admisionesHospitalarias: initialAdmisionesHospitalarias,
  registrosTriaje: initialRegistrosTriaje,
  odontogramas: initialOdontogramas,
  teleconsultas: initialTeleconsultas,
  interconsultas: initialInterconsultas,
  serviciosTarifas: initialServiciosTarifas,
  facturas: initialFacturas,
  registrosAuditoria: initialRegistrosAuditoria,
  casosEpidemiologicos: initialCasosEpidemiologicos
});

